spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: ${FLYWAY_ENABLED}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: true

authentication:
  jwt:
    expiration: 1h
    secret: KL4xHZeqaesSNpfonXEnTd3FMG3fUQYyXkYUvYCyuoE=

external:
  aws:
    s3:
      region: ${AWS_S3_REGION}
      attachment:
        bucket:
          name: ${AWS_S3_ATTACHMENT_BUCKET_NAME}
        key:
          prefix: ${AWS_S3_ATTACHMENT_KEY_PREFIX}
