spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: composite

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: ${FLYWAY_ENABLED}
    locations: ${FLYWAY_LOCATIONS}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
